### ISSUE TITLE
cant start the app

### ISSUE THREAD

**Issue by dpreussler** [SigmaLibrae/MoviesApp#1]
Process: com.siegmund.moviesapp, PID: 3328
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'int com.siegmund.moviesapp.api.MovieResponse.getPage()' on a null object reference
                                                                          at com.siegmund.moviesapp.ui.main.MainPresenter$loadMoviesForPage$1$1.onResponse(MainPresenter.kt:34)
                                                                          at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by dpreussler** [comment]
was missing API key
